### ISSUE TITLE
Task List - Management

### ISSUE THREAD

**Issue by cfree** [denvercodeclub/denvercodeclub-com#4]
Get halfway through the list:
- [x] Management
  - [X] Determine Project - Create a website to both advertise and inform the public about the group.
    - [X] Determine Deliverables
      - Deployable website
    - [X] Define Stakeholders
      - Sponsors
      - New members
      - Current members
  - [X] [Needs Assessment / Discovery](https://github.com/denvercodeclub/denvercodeclub-com/wiki/Project-Discovery)
  - [X] Determine Tech Stack
    - AngularJS
    - Sass
      - Susy
    - jQuery
    - Server (TBD)
      - Apache / MySQL / Laravel
      - Node.js / MongoDB / Express.js
  - [X] Browser support matrix
    - IE9+
    - Safari
    - Chrome
    - Firefox
  - [X] Determine style guides - When we review pull requests, not only will we be checking for correct and efficient code, but we'll be comparing it against the appropriate style guides listed below. This way, we are all adhering to the same style.
    - [CSS](https://github.com/necolas/idiomatic-css)
    - [JavaScript](https://github.com/rwaldron/idiomatic.js)
    - [PHP](https://make.wordpress.org/core/handbook/coding-standards/php/)
    - [HTML](https://github.com/styleguide/templates)
    - [Angular](https://github.com/johnpapa/angularjs-styleguide)
